name: Build Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Create Directories
      shell: cmd
      run: |
        mkdir templates
        mkdir uploads
        mkdir assets
        dir
        
    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install flask tabula-py pandas openpyxl pillow pystray pyinstaller jpype1
        pip list
        
    - name: Build with PyInstaller
      shell: cmd
      run: |
        set JAVA_HOME=%JAVA_HOME_17_X64%
        echo %JAVA_HOME%
        dir "%JAVA_HOME%\bin"
        python -m PyInstaller --clean --log-level DEBUG pdf_extractor.spec
        dir dist
        
    - name: Create ZIP archive
      shell: cmd
      run: |
        cd dist
        powershell Compress-Archive -Path PDFTableExtractor -DestinationPath PDFTableExtractor-Windows.zip
        dir
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PDFTableExtractor-Windows
        path: dist/PDFTableExtractor-Windows.zip 